"""empty message

Revision ID: 14200d694948
Revises: 77b95441a7d7
Create Date: 2024-04-30 19:01:35.540205

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14200d694948"
down_revision = "77b95441a7d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuration",
        sa.Column(
            "photo_url",
            sa.UnicodeText(),
            server_default='{{ standard["photo_url"] }}',
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuration", "photo_url")
    # ### end Alembic commands ###
