"""empty message

Revision ID: 38ed85bb31ec
Revises: 14200d694948
Create Date: 2024-11-26 17:48:33.200453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ed85bb31ec'
down_revision = '14200d694948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('photo_copyright_text', sa.UnicodeText(), server_default='{{ standard["photo_copyright_text"] }}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'photo_copyright_text')
    # ### end Alembic commands ###
