"""empty message

Revision ID: d43954ccfb3b
Revises: e9a8d9dedfe0
Create Date: 2024-02-23 22:28:32.772779

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d43954ccfb3b"
down_revision = "e9a8d9dedfe0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuration",
        sa.Column(
            "tags",
            sa.UnicodeText(),
            server_default='{{ standard["tags"] }}',
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuration", "tags")
    # ### end Alembic commands ###
